language: python
install:
  - pip install rstcheck
  - pip install -e ./
  - pip install pycodestyle
script:
  - rstcheck README.rst
  - dluxparser --help
  - dluxparser csv2json -h
  - pycodestyle dluxparser/*.py
